### ISSUE TITLE
Tetragon v0.11.0 eBPF verifier fail on Rocky Linux 8.6 kernel 4.18

### ISSUE THREAD

**Issue by miloaissatu** [cilium/tetragon#1442] opened 2023-09-08 01:15 UTC
### What happened?

Environment:
* Rancher Kubernetes (RKE2), Kubernetes version v1.26.7+rke2r1
* underlying host kernel 4.18.0-372.32.1.el8_6.x86_64
* underlying host OS Rocky Linux release 8.6 (Green Obsidian)

Using default values.yaml https://github.com/cilium/tetragon/blob/v0.11.0/install/kubernetes/values.yaml

`helm install tetragon cilium/tetragon -n kube-system`

tetragon pod's tetragon container is in crashloopbackoff with this error
```+ kubectl logs tetragon-dcc7m tetragon
...
time="2023-09-08T01:11:26Z" level=info msg="Loading registered BPF probe" Program=/var/lib/tetragon/bpf_execve_event.o Type=execve
time="2023-09-08T01:11:26Z" level=info msg="BPF events statistics: 0 received, 0% events loss"
time="2023-09-08T01:11:26Z" level=info msg="Observer events statistics" errors=0 filterDrop=0 filterPass=0 lost=0 received=0
time="2023-09-08T01:11:26Z" level=info msg="sensor controller starts"
time="2023-09-08T01:11:26Z" level=info msg="BPF prog was unloaded" label=kprobe/do_task_dead pin=event_exit
time="2023-09-08T01:11:26Z" level=info msg="BPF prog was unloaded" label=kprobe/wake_up_new_task pin=kprobe_pid_clear
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_map pin=execve_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_map_stats pin=execve_map_stats
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_calls pin=execve_calls
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=names_map pin=names_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=tcpmon_map pin=tcpmon_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=tg_conf_map pin=tg_conf_map
time="2023-09-08T01:11:26Z" level=fatal msg="Failed to start tetragon" error="failed prog /var/lib/tetragon/bpf_execve_event.o kern_version 266752 loadInstance: opening collection '/var/lib/tetragon/bpf_execve_event.o' failed: program event_execve: load program: invalid argument: value -2147483648 makes ctx pointer be out of bounds (935 line(s) omitted)"
```

### Tetragon Version

v0.11.0 deployed via helm chart
init container / tetragon operator: quay.io/cilium/tetragon-operator:v0.11.0
tetragon container image: quay.io/cilium/tetragon:v0.11.0

### Kernel Version

Rocky Linux release 8.6 (Green Obsidian) kernel 4.18.0-372.32.1.el8_6.x86_64

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7+rke2r1", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T20:19:16Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Relevant log output

```shell
#Entire tetragon log output
time="2023-09-08T01:11:26Z" level=info msg="Loaded config from directory" config-dir=/etc/tetragon/tetragon.conf.d/
time="2023-09-08T01:11:26Z" level=info msg="Starting gops server" addr="localhost:8118"
time="2023-09-08T01:11:26Z" level=info msg="Starting tetragon" version=v0.11.0
time="2023-09-08T01:11:26Z" level=info msg="config settings" config="map[bpf-lib:/var/lib/tetragon/ btf: cilium-bpf: config-dir:/etc/tetragon/tetragon.conf.d/ config-file: cpuprofile: data-cache-size:1024 debug:false disable-kprobe-multi:false enable-cilium-api:false enable-export-aggregation:false enable-k8s-api:true enable-msg-handling-latency:false enable-pid-set-filter:false enable-policy-filter:false enable-policy-filter-debug:false enable-process-ancestors:true enable-process-cred:false enable-process-ns:false event-queue-size:10000 export-aggregation-buffer-size:10000 export-aggregation-window-size:15s export-allowlist:{\"event_set\":[\"PROCESS_EXEC\", \"PROCESS_EXIT\", \"PROCESS_KPROBE\", \"PROCESS_UPROBE\"]} export-denylist:{\"health_check\":true}\n{\"namespace\":[\"\", \"cilium\", \"kube-system\"]} export-file-compress:false export-file-max-backups:5 export-file-max-size-mb:10 export-file-rotation-interval:0s export-filename:/var/run/cilium/tetragon/tetragon.log export-rate-limit:-1 field-filters:{} force-large-progs:false force-small-progs:false gops-address:localhost:8118 k8s-kubeconfig-path: kernel: kmods:[] log-format:text log-level:info memprofile: metrics-server::2112 netns-dir:/var/run/docker/netns/ pprof-addr: process-cache-size:65536 procfs:/procRoot rb-size:0 rb-size-total:0 release-pinned-bpf:true server-address:localhost:54321 tracing-policy: tracing-policy-dir:/etc/tetragon/tetragon.tp.d verbose:0]"
time="2023-09-08T01:11:26Z" level=info msg="BPF: successfully released pinned BPF programs and maps" bpf-dir=/sys/fs/bpf/tetragon
time="2023-09-08T01:11:26Z" level=info msg="BTF discovery: default kernel btf file found" btf-file=/sys/kernel/btf/vmlinux
time="2023-09-08T01:11:26Z" level=info msg="sensor controller waiting on channel"
time="2023-09-08T01:11:26Z" level=info msg="Starting metrics server" addr=":2112"
time="2023-09-08T01:11:26Z" level=info msg="Registering pod delete handler for metrics"
time="2023-09-08T01:11:26Z" level=info msg="Cgroup mode detection succeeded" cgroup.fs=/sys/fs/cgroup cgroup.mode="Legacy mode (Cgroupv1)"
time="2023-09-08T01:11:26Z" level=info msg="Supported cgroup controller 'memory' is active on the system" cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:11:26Z" level=info msg="Supported cgroup controller 'pids' is active on the system" cgroup.controller.hierarchyID=12 cgroup.controller.index=11 cgroup.controller.name=pids cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:11:26Z" level=info msg="Supported cgroup controller 'cpuset' is active on the system" cgroup.controller.hierarchyID=9 cgroup.controller.index=0 cgroup.controller.name=cpuset cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:11:26Z" level=info msg="Cgroupv1 controller 'memory' will be used" cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:11:26Z" level=info msg="Cgroupv1 hierarchy validated successfully" cgroup.fs=/sys/fs/cgroup cgroup.path=/sys/fs/cgroup/memory
time="2023-09-08T01:11:26Z" level=info msg="Deployment mode detection succeeded" cgroup.fs=/sys/fs/cgroup deployment.mode=Kubernetes
time="2023-09-08T01:11:26Z" level=info msg="Updated TetragonConf map successfully" NSPID=1 cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs.magic=Cgroupv1 confmap-update=tg_conf_map deployment.mode=Kubernetes log.level=info
time="2023-09-08T01:11:26Z" level=info msg="Enabling Kubernetes API"
time="2023-09-08T01:11:26Z" level=info msg="registering policyfilter pod handlers"
time="2023-09-08T01:11:26Z" level=info msg="Initialized pod cache" num_pods=26
time="2023-09-08T01:11:26Z" level=info msg="Initialized service cache" num_services=9
time="2023-09-08T01:11:26Z" level=info msg="Disabling Cilium API"
time="2023-09-08T01:11:26Z" level=info msg="Starting process manager" enableCilium=false enableK8s=true enableProcessCred=false enableProcessNs=false
time="2023-09-08T01:11:26Z" level=info msg="Starting gRPC server" address="localhost:54321" protocol=tcp
time="2023-09-08T01:11:26Z" level=info msg="Starting JSON exporter" logger="&{/var/run/cilium/tetragon/tetragon.log 10 0 5 false false ---------- 0 <nil> {0 0} <nil> {0 {0 0}}}" request="allow_list:{event_set:PROCESS_EXEC  event_set:PROCESS_EXIT  event_set:PROCESS_KPROBE  event_set:PROCESS_UPROBE}  deny_list:{health_check:{value:true}}  deny_list:{namespace:\"\"  namespace:\"cilium\"  namespace:\"kube-system\"}  field_filters:{}"
time="2023-09-08T01:11:26Z" level=info msg="Exporter configuration" enabled=true fileName=/var/run/cilium/tetragon/tetragon.log
time="2023-09-08T01:11:26Z" level=info msg="Successfully detected bpftool path" bpftool=/usr/bin/bpftool
time="2023-09-08T01:11:26Z" level=info msg="BPF: found active BPF resources" bpf-dir=/sys/fs/bpf/tetragon pinned-bpf="[tg_conf_map]"
time="2023-09-08T01:11:26Z" level=info msg="BTF file: using metadata file" metadata=/sys/kernel/btf/vmlinux
time="2023-09-08T01:11:26Z" level=info msg="Loading sensor" name=__base__
time="2023-09-08T01:11:26Z" level=info msg="Loading kernel version 4.18.0"
time="2023-09-08T01:11:26Z" level=info msg="Started watching tracing policies"
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=execve_map path=/sys/fs/bpf/tetragon/execve_map sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=execve_map_stats path=/sys/fs/bpf/tetragon/execve_map_stats sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=execve_calls path=/sys/fs/bpf/tetragon/execve_calls sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=names_map path=/sys/fs/bpf/tetragon/names_map sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=tcpmon_map path=/sys/fs/bpf/tetragon/tcpmon_map sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="tetragon, map loaded." map=tg_conf_map path=/sys/fs/bpf/tetragon/tg_conf_map sensor=__base__
time="2023-09-08T01:11:26Z" level=info msg="Loading BPF program" Program=/var/lib/tetragon/bpf_exit.o Type=kprobe
time="2023-09-08T01:11:26Z" level=info msg="Loading BPF program" Program=/var/lib/tetragon/bpf_fork.o Type=kprobe
time="2023-09-08T01:11:26Z" level=info msg="Loading registered BPF probe" Program=/var/lib/tetragon/bpf_execve_event.o Type=execve
time="2023-09-08T01:11:26Z" level=info msg="BPF events statistics: 0 received, 0% events loss"
time="2023-09-08T01:11:26Z" level=info msg="Observer events statistics" errors=0 filterDrop=0 filterPass=0 lost=0 received=0
time="2023-09-08T01:11:26Z" level=info msg="sensor controller starts"
time="2023-09-08T01:11:26Z" level=info msg="BPF prog was unloaded" label=kprobe/do_task_dead pin=event_exit
time="2023-09-08T01:11:26Z" level=info msg="BPF prog was unloaded" label=kprobe/wake_up_new_task pin=kprobe_pid_clear
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_map pin=execve_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_map_stats pin=execve_map_stats
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=execve_calls pin=execve_calls
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=names_map pin=names_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=tcpmon_map pin=tcpmon_map
time="2023-09-08T01:11:26Z" level=info msg="map was unloaded" map=tg_conf_map pin=tg_conf_map
time="2023-09-08T01:11:26Z" level=fatal msg="Failed to start tetragon" error="failed prog /var/lib/tetragon/bpf_execve_event.o kern_version 266752 loadInstance: opening collection '/var/lib/tetragon/bpf_execve_event.o' failed: program event_execve: load program: invalid argument: value -2147483648 makes ctx pointer be out of bounds (935 line(s) omitted)"
```

**Comment by miloaissatu** [comment] 2023-09-08 01:20
version 0.10.0 is able to start, new to tetragon so not entirely sure if its fully functional (yet) :)

logs from 0.10.0
```
+ kubectl logs -f tetragon-k78ft tetragon
time="2023-09-08T01:18:55Z" level=info msg="Loaded config from directory" config-dir=/etc/tetragon/tetragon.conf.d/
time="2023-09-08T01:18:55Z" level=info msg="Starting gops server" addr="localhost:8118"
time="2023-09-08T01:18:55Z" level=info msg="Starting tetragon" version=v0.10.0
time="2023-09-08T01:18:55Z" level=info msg="config settings" config="map[bpf-lib:/var/lib/tetragon/ btf: cilium-bpf: config-dir:/etc/tetragon/tetragon.conf.d/ config-file: cpuprofile: data-cache-size:1024 debug:false disable-kprobe-multi:false enable-cilium-api:false enable-export-aggregation:false enable-k8s-api:true enable-msg-handling-latency:false enable-pid-set-filter:false enable-policy-filter:false enable-policy-filter-debug:false enable-process-ancestors:true enable-process-cred:false enable-process-ns:false event-queue-size:10000 export-aggregation-buffer-size:10000 export-aggregation-window-size:15s export-allowlist:{\"event_set\":[\"PROCESS_EXEC\", \"PROCESS_EXIT\", \"PROCESS_KPROBE\", \"PROCESS_UPROBE\"]} export-denylist:{\"health_check\":true}\n{\"namespace\":[\"\", \"cilium\", \"kube-system\"]} export-file-compress:false export-file-max-backups:5 export-file-max-size-mb:10 export-file-rotation-interval:0s export-filename:/var/run/cilium/tetragon/tetragon.log export-rate-limit:-1 field-filters:{} force-large-progs:false force-small-progs:false gops-address:localhost:8118 k8s-kubeconfig-path: kernel: log-format:text log-level:info memprofile: metrics-server::2112 netns-dir:/var/run/docker/netns/ pprof-addr: process-cache-size:65536 procfs:/procRoot rb-size:0 rb-size-total:0 release-pinned-bpf:true server-address:localhost:54321 tracing-policy: verbose:0]"
time="2023-09-08T01:18:55Z" level=info msg="BPF: successfully released pinned BPF programs and maps" bpf-dir=/sys/fs/bpf/tetragon
time="2023-09-08T01:18:55Z" level=info msg="BTF discovery: default kernel btf file found" btf-file=/sys/kernel/btf/vmlinux
time="2023-09-08T01:18:55Z" level=info msg="Cgroup mode detection succeeded" cgroup.fs=/sys/fs/cgroup cgroup.mode="Legacy mode (Cgroupv1)"
time="2023-09-08T01:18:55Z" level=info msg="sensor controller waiting on channel"
time="2023-09-08T01:18:55Z" level=info msg="Starting metrics server" addr=":2112"
time="2023-09-08T01:18:55Z" level=info msg="Supported cgroup controller 'memory' is active on the system" cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:18:55Z" level=info msg="Supported cgroup controller 'pids' is active on the system" cgroup.controller.hierarchyID=12 cgroup.controller.index=11 cgroup.controller.name=pids cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:18:55Z" level=info msg="Supported cgroup controller 'cpuset' is active on the system" cgroup.controller.hierarchyID=9 cgroup.controller.index=0 cgroup.controller.name=cpuset cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:18:55Z" level=info msg="Cgroupv1 controller 'memory' will be used" cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs=/sys/fs/cgroup
time="2023-09-08T01:18:55Z" level=info msg="Cgroupv1 hierarchy validated successfully" cgroup.fs=/sys/fs/cgroup cgroup.path=/sys/fs/cgroup/memory
time="2023-09-08T01:18:55Z" level=info msg="Deployment mode detection succeeded" cgroup.fs=/sys/fs/cgroup deployment.mode=Kubernetes
time="2023-09-08T01:18:55Z" level=info msg="Updated TetragonConf map successfully" NSPID=1 cgroup.controller.hierarchyID=6 cgroup.controller.index=4 cgroup.controller.name=memory cgroup.fs.magic=Cgroupv1 confmap-update=tg_conf_map deployment.mode=Kubernetes log.level=info
time="2023-09-08T01:18:55Z" level=info msg="Enabling Kubernetes API"
time="2023-09-08T01:18:55Z" level=info msg="registering policyfilter pod handlers"
time="2023-09-08T01:18:55Z" level=info msg="Initialized pod cache" num_pods=26
time="2023-09-08T01:18:55Z" level=info msg="Disabling Cilium API"
time="2023-09-08T01:18:55Z" level=info msg="Starting process manager" enableCilium=false enableK8s=true enableProcessCred=false enableProcessNs=false
time="2023-09-08T01:18:55Z" level=info msg="Starting gRPC server" address="localhost:54321" protocol=tcp
time="2023-09-08T01:18:55Z" level=info msg="Starting JSON exporter" logger="&{/var/run/cilium/tetragon/tetragon.log 10 0 5 false false ---------- 0 <nil> {0 0} <nil> {0 {0 0}}}" request="allow_list:{event_set:PROCESS_EXEC event_set:PROCESS_EXIT event_set:PROCESS_KPROBE event_set:PROCESS_UPROBE} deny_list:{health_check:{value:true}} deny_list:{namespace:\"\" namespace:\"cilium\" namespace:\"kube-system\"} field_filters:{}"
time="2023-09-08T01:18:55Z" level=info msg="Exporter configuration" enabled=true fileName=/var/run/cilium/tetragon/tetragon.log
time="2023-09-08T01:18:55Z" level=info msg="Successfully detected bpftool path" bpftool=/usr/bin/bpftool
time="2023-09-08T01:18:55Z" level=info msg="BPF: found active BPF resources" bpf-dir=/sys/fs/bpf/tetragon pinned-bpf="[tg_conf_map]"
time="2023-09-08T01:18:55Z" level=info msg="BTF file: using metadata file" metadata=/sys/kernel/btf/vmlinux
time="2023-09-08T01:18:55Z" level=info msg="Loading sensor" name=__base__
time="2023-09-08T01:18:55Z" level=info msg="Loading kernel version 4.18.0"
time="2023-09-08T01:18:55Z" level=info msg="Started watching tracing policies"
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=execve_map path=/sys/fs/bpf/tetragon/execve_map sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=execve_map_stats path=/sys/fs/bpf/tetragon/execve_map_stats sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=execve_calls path=/sys/fs/bpf/tetragon/execve_calls sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=names_map path=/sys/fs/bpf/tetragon/names_map sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=tcpmon_map path=/sys/fs/bpf/tetragon/tcpmon_map sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="tetragon, map loaded." map=tg_conf_map path=/sys/fs/bpf/tetragon/tg_conf_map sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="Loading BPF program" Program=/var/lib/tetragon/bpf_exit.o Type=kprobe
time="2023-09-08T01:18:55Z" level=info msg="Loading BPF program" Program=/var/lib/tetragon/bpf_fork.o Type=kprobe
time="2023-09-08T01:18:55Z" level=info msg="Loading registered BPF probe" Program=/var/lib/tetragon/bpf_execve_event.o Type=execve
time="2023-09-08T01:18:55Z" level=info msg="Read ProcFS /procRoot appended 156/736 entries"
time="2023-09-08T01:18:55Z" level=warning msg="Procfs execve event pods/ identifier error" error="open /procRoot/0/cgroup: no such file or directory"
time="2023-09-08T01:18:55Z" level=info msg="Loaded BPF maps and events for sensor successfully" sensor=__base__
time="2023-09-08T01:18:55Z" level=info msg="sensor controller starts"
time="2023-09-08T01:18:55Z" level=info msg="Available sensors" sensors=
time="2023-09-08T01:18:55Z" level=info msg="Registered sensors (policy-handlers)" policy-handlers="uprobe sensor, loader sensor, tracing"
time="2023-09-08T01:18:55Z" level=info msg="Registered probe types" types="generic_uprobe, loader, execve, generic_kprobe, generic_tracepoint"
time="2023-09-08T01:18:55Z" level=info msg="Perf ring buffer size (bytes)" percpu=69632 total=3620864
time="2023-09-08T01:18:55Z" level=info msg="Listening for events..."
```

**Comment by YanjiangChen** [comment] 2023-09-08 07:15
I also have the same problem. Is there any solution?

**Comment by YanjiangChen** [comment] 2023-09-08 07:15
time="2023-09-08T03:11:08-04:00" level=info msg="Loading kernel version 4.18.0"
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=execve_map path=/sys/fs/bpf/tetragon/execve_map sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=execve_map_stats path=/sys/fs/bpf/tetragon/execve_map_stats sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=execve_calls path=/sys/fs/bpf/tetragon/execve_calls sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=names_map path=/sys/fs/bpf/tetragon/names_map sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=tcpmon_map path=/sys/fs/bpf/tetragon/tcpmon_map sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="tetragon, map loaded." map=tg_conf_map path=/sys/fs/bpf/tetragon/tg_conf_map sensor=__base__
time="2023-09-08T03:11:08-04:00" level=info msg="Loading BPF program" Program=bpf/objs/bpf_exit.o Type=kprobe
time="2023-09-08T03:11:08-04:00" level=info msg="Loading BPF program" Program=bpf/objs/bpf_fork.o Type=kprobe
time="2023-09-08T03:11:08-04:00" level=info msg="Loading registered BPF probe" Program=bpf/objs/bpf_execve_event.o Type=execve
time="2023-09-08T03:11:08-04:00" level=info msg="BPF events statistics: 0 received, 0% events loss"
time="2023-09-08T03:11:08-04:00" level=info msg="Observer events statistics" errors=0 filterDrop=0 filterPass=0 lost=0 received=0
time="2023-09-08T03:11:08-04:00" level=info msg="sensor controller starts"
time="2023-09-08T03:11:09-04:00" level=info msg="BPF prog was unloaded" label=kprobe/do_task_dead pin=event_exit
time="2023-09-08T03:11:09-04:00" level=info msg="BPF prog was unloaded" label=kprobe/wake_up_new_task pin=kprobe_pid_clear
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=execve_map pin=execve_map
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=execve_map_stats pin=execve_map_stats
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=execve_calls pin=execve_calls
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=names_map pin=names_map
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=tcpmon_map pin=tcpmon_map
time="2023-09-08T03:11:09-04:00" level=info msg="map was unloaded" map=tg_conf_map pin=tg_conf_map
time="2023-09-08T03:11:09-04:00" level=fatal msg="Failed to start tetragon" error="failed prog bpf/objs/bpf_execve_event.o kern_version 266752 loadInstance: opening collection 'bpf/objs/bpf_execve_event.o' failed: program event_execve: load program: invalid argument: value -2147483648 makes ctx pointer be out of bounds (935 line(s) omitted)"
[root@dev-rhel8-101-41

**Comment by mtardy** [comment] 2023-09-08 08:11
Thanks for the report, we will try to reproduce and investigate this issue.

**Comment by mtardy** [comment] 2023-09-08 08:46
So as a first answer, I can understand that this is not the most satisfactory, but we don't test and thus support Tetragon on non-stable kernels, you can see on this workflow for example that we test the 4 stables kernels pre-6 and bpf-next https://github.com/cilium/tetragon/actions/runs/6110916768. I guess the rocky Linux 8.6 kernel is a modified 4.18 kernel.

However, I spawned a VM with approximately the same kernel and bisected the issue to this commit 830667658a7046b43ca4e945ee52219670b7c40c which might be what breaks the verifier on this kernel.

**Comment by YanjiangChen** [comment] 2023-09-11 10:12
I think this is not good. It means that as Tetragon versions are updated, more and more kernels may be abandoned. This is not user-friendly for users who are using the initial version.

**Comment by mtardy** [comment] 2023-09-12 13:07
Good news @YanjiangChen, Kornilios submitted a patch that should solve this and should be backported to v0.11.0 so that v0.11.1 will contain the fix. See https://github.com/cilium/tetragon/pull/1454.

**Comment by kkourt** [comment] 2023-09-12 15:44
@YanjiangChen Since #1454 was merged, could you try and see if the problem persists with `:latest`? If it does, could you please reopen this issue? Thanks!

**Closed by kkourt** 2023-09-12 15:44 UTC
Labels: kind/bug
