### ISSUE TITLE
Replace the use of `viper.BindPFlags` with variables binding

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#1108] opened 2023-06-22 08:26 UTC
Replace all use of `viper.BindPFlags` with flag variables like here https://github.com/cilium/tetragon/pull/1106/commits/da795ea4b2890f51f2f922a19e194ac3926a0429 and add a static check on `BindPFlags`, like grep or something like that to prevent the use of this thing. Because:

> When using same local flag for different subcommands, binding to the global configuration will erase previous values with the value of the last command's flag registered. See https://github.com/spf13/viper/issues/233.

And this has been breaking flags for some time now.

**Comment by Jack-R-lantern** [comment] 2023-06-23 14:38
Can I be assigned this issue?

**Comment by Jack-R-lantern** [comment] 2023-10-27 13:10
@mtardy

I apologize for leaving the issue unattended for so long.
While revisiting this issue recently, I noticed that the code has changed quite a bit since the issue was first published.
So I think it's worth checking to see if the issue is still valid.

**Comment by mtardy** [comment] 2023-10-27 13:13
> @mtardy
> 
> I apologize for leaving the issue unattended for so long. While revisiting this issue recently, I noticed that the code has changed quite a bit since the issue was first published. So I think it's worth checking to see if the issue is still valid.

no worries, yep the option/flags part changed quite a lot recently. I would say it still applies but it's up to you, you can pick up something else and we can close this one. This thing has been causing issues in the past but it's not technically broken at the moment, it's mostly preventive.

**Comment by Jack-R-lantern** [comment] 2023-10-29 07:54
For cmd/tetra, I think the change to viper.BindPFlags is valid.
However, in cmd/tetragon, the operator is calling viper.MergeConfigMap via pkg/option's Read*Config function.
Therefore, in both cases, we believe the use of viper.BindPFlags is appropriate.
What are your thoughts on this?

**Comment by mtardy** [comment] 2023-11-02 10:50
> @mtardy For cmd/tetra, I think the change to viper.BindPFlags is valid. However, in cmd/tetragon, the operator is calling viper.MergeConfigMap via pkg/option's Read*Config function. Therefore, in both cases, we believe the use of viper.BindPFlags is appropriate. What are your thoughts on this?

let's worry only about `tetra` because `tetragon` is less subject having multiple flags colliding. I think your PR is great for tetra :)

**Closed** 2023-11-15 12:54 UTC
Labels: good first issue, area/userspace
