### ISSUE TITLE
ci flake: TestKprobeObjectOpenMount occaisionally failing

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#285] opened 2022-08-03 15:07 UTC
Noticed a new CI flake today where TestKprobeObjectOpenMount seems to be missing the expected `ProcessKprobe` event [here][0]. In fact, we do not see any PROCESS_KPROBE events at all.

[0]: https://github.com/cilium/tetragon/runs/7654593505?check_suite_focus=true#step:7:469

**Comment by tpapagian** [comment] 2022-08-03 16:57
This seems related to OOO events. I reproduced that in https://github.com/cilium/tetragon/pull/286 where I have just do some prints and I can see `"kprobe event is cached!"` in the logs for the failed test.

The design of the cache requires about ~10seconds to produce an event if the exec event comes after the kprobe event, and most possibly this is the reason for the missing kprobe events. 

I am assigning this to myself as I am currently working on OOO events. Maybe an easy solution can be to increase the timeout in kprobe tests but I will check it if there can be a better solution. 

Maybe https://github.com/cilium/tetragon/issues/247 is also related to this one.

**Comment by kkourt** [comment] 2022-08-05 07:53
> The design of the cache requires about ~10seconds to produce an event if the exec event comes after the kprobe event, and most possibly this is the reason for the missing kprobe events.

It might be useful to have metrics for out of order events in the cache to track these cases.

**Closed** 2022-08-08 15:52 UTC
Labels: area/tracing, kind/ci-flake
