### ISSUE TITLE
Generic tracing example policy not working 

### ISSUE THREAD

**Issue by YogevMaty** [cilium/tetragon#1081] opened 2023-06-14 13:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using the examples provided I am getting the following error

kubectl apply -f https://raw.githubusercontent.com/cilium/tetragon/main/examples/tracingpolicy/tcp-connect.yaml
The TracingPolicy "connect" is invalid: spec.kprobes.selectors.matchArgs.operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"

### Tetragon Version

I was using the helm chart you provided in the installation guid (Deploy Tetragon section)

### Kernel Version

Linux My.Host.Name 5.15.108 #1 SMP Tue May 9 23:53:46 UTC 2023 x86_64 GNU/Linux

### Kubernetes Version

v1.23.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jacobcrawford** [comment] 2023-06-16 10:11
This is not a bug. The examples in the readme were merged to the main branch before the version of Tetragon supporting the "DAddr" operator has been released. 
The functionality for "DAddr" is on the main branch as well, but no helm chart

**Comment by mtardy** [comment] 2023-06-19 08:33
Yes exact, you'll need to run the latest build from main, you can do this with:
```shell
helm -n kube-system upgrade --install tetragon cilium/tetragon --set tetragon.image.override=quay.io/cilium/tetragon-ci:latest --set tetragonOperator.image.override=quay.io/cilium/tetragon-operator-ci:latest --set imagePullPolicy=Always
```

Double-check that the installed CRDs in your cluster were upgraded.

Indeed it's not convenient since Tetragon is versioned while our TracingPolicies examples are not, so mismatchs happen :/

**Comment by mtardy** [comment] 2023-06-28 09:00
As we answer this question, I'll close this issue. Please comment again or reopen if you don't agree.

**Comment by snowline2015** [comment] 2023-07-02 08:56
I have already executed the provided command, but unfortunately, I am still encountering the following error:

`The TracingPolicy "connect" is invalid: 
* spec.kprobes[0].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
* spec.kprobes[1].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
* spec.kprobes[2].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"`

I would appreciate any further guidance. Thank you in advanced !

**Comment by mtardy** [comment] 2023-07-02 19:42
> Hi, I have already executed the provided command, but unfortunately, I am still encountering the following error:
> 
> 
> 
> ```
> 
> The TracingPolicy "connect" is invalid: 
> 
> spec.kprobes[0].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
> 
> spec.kprobes[1].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
> 
> spec.kprobes[2].selectors[0].matchArgs[0].operator: Unsupported value: "DAddr": supported values: "Equal", "NotEqual", "Prefix", "Postfix"
> 
> ```
> 
> 
> 
> I would appreciate any further guidance. Thank you in advance !

Hey! Let me reopen this issue, clearly we indeed have trouble there as we received multiple reports like that. I'll address this issue this week and get back to you.

**Comment by kevsecurity** [comment] 2023-07-03 12:49
I’ve reverted the changes to the tcp-connect.yaml example so hopefully it will work now.

**Comment by snowline2015** [comment] 2023-07-04 07:15
Thanks ! It's now working.

**Closed** 2023-07-06 12:32 UTC
Labels: question
